volumes:
  pentagi-data:
    driver: local
  pentagi-ssl:
    driver: local
  pentagi-ollama:
    driver: local
  scraper-ssl:
    driver: local
  pentagi-postgres-data:
    driver: local

networks:
  pentagi-network:
    driver: bridge
    name: pentagi-network

services:
  pentagi:
    image: ${PENTAGI_IMAGE:-vxcontrol/pentagi:latest}
    restart: unless-stopped
    container_name: pentagi
    hostname: pentagi
    extra_hosts:
      - "host.docker.internal:host-gateway" # 关键：访问宿主机Ollama
    expose:
      - 8443/tcp
    ports:
      - 0.0.0.0:${PENTAGI_LISTEN_PORT:-8443}:8443
    depends_on:
      pgvector:
        condition: service_healthy
    env_file: .env
    logging:
      options:
        max-size: 50m
        max-file: "7"
    volumes:
      - ${PENTAGI_DATA_DIR:-pentagi-data}:/opt/pentagi/data
      - ${PENTAGI_SSL_DIR:-pentagi-ssl}:/opt/pentagi/ssl
      - ${PENTAGI_OLLAMA_DIR:-pentagi-ollama}:/root/.ollama
      - ${PENTAGI_DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      - ${PENTAGI_LLM_SERVER_CONFIG_PATH:-./example.custom.provider.yml}:/opt/pentagi/conf/custom.provider.yml
      - ${PENTAGI_OLLAMA_SERVER_CONFIG_PATH:-./example.ollama.provider.yml}:/opt/pentagi/conf/ollama.provider.yml
      - ${PENTAGI_DOCKER_CERT_PATH:-./docker-ssl}:/opt/pentagi/docker/ssl
    user: root:root # 使用docker.sock必须root
    networks:
      - pentagi-network

  pgvector:
    image: vxcontrol/pgvector:latest
    restart: unless-stopped
    container_name: pgvector
    hostname: pgvector
    expose:
      - 5432/tcp
    ports:
      - 127.0.0.1:${PGVECTOR_LISTEN_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${PENTAGI_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${PENTAGI_POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${PENTAGI_POSTGRES_DB:-pentagidb}
    logging:
      options:
        max-size: 50m
        max-file: "7"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${PENTAGI_POSTGRES_USER:-postgres}"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
    volumes:
      - pentagi-postgres-data:/var/lib/postgresql/data
    networks:
      - pentagi-network

  pgexporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.16.0
    restart: unless-stopped
    depends_on:
      pgvector:
        condition: service_healthy
    container_name: pgexporter
    hostname: pgexporter
    expose:
      - 9187/tcp
    ports:
      - 127.0.0.1:${POSTGRES_EXPORTER_LISTEN_PORT:-9187}:9187
    environment:
      - DATA_SOURCE_NAME=postgresql://${PENTAGI_POSTGRES_USER:-postgres}:${PENTAGI_POSTGRES_PASSWORD:-postgres}@pgvector:5432/${PENTAGI_POSTGRES_DB:-pentagidb}?sslmode=disable
    logging:
      options:
        max-size: 50m
        max-file: "7"
    networks:
      - pentagi-network

  scraper:
    image: vxcontrol/scraper:latest
    restart: unless-stopped
    container_name: scraper
    hostname: scraper
    expose:
      - 443/tcp
    ports:
      - 127.0.0.1:${SCRAPER_LISTEN_PORT:-9443}:443
    environment:
      - MAX_CONCURRENT_SESSIONS=${LOCAL_SCRAPER_MAX_CONCURRENT_SESSIONS:-10}
      - USERNAME=${LOCAL_SCRAPER_USERNAME:-someuser}
      - PASSWORD=${LOCAL_SCRAPER_PASSWORD:-somepass}
    logging:
      options:
        max-size: 50m
        max-file: "7"
    volumes:
      - scraper-ssl:/usr/src/app/ssl
    networks:
      - pentagi-network
    shm_size: 2g
